// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    wp.customize('sidebar_featured_enabled', function(val) {
      return val.bind(function(newval) {
        if (newval === true) {
          return $('.nav-hot').show();
        }
        return $('.nav-hot').hide();
      });
    });
    return wp.customize('sidebar_featured_text', function(val) {
      return val.bind(function(newval) {
        return $('.nav-hot').html(newval);
      });
    });
  })(jQuery);

}).call(this);

//# sourceMappingURL=customizer.map
